--CONTEO DE DEVICE POR APPLICATION_USER_ID
SELECT
    REGISTER_DEVICE
     ,COUNT(APPLICATION_USER_ID) AS DEVICE_COUNT
FROM user_entity
WHERE 1 = 1
  AND REGISTER_DEVICE <> 'OTRO'
GROUP BY REGISTER_DEVICE
ORDER BY DEVICE_COUNT DESC;

--CONTEO DE GENERO POR APPLICATION_USER_ID
SELECT
    GENDER
     ,COUNT(APPLICATION_USER_ID) AS GENDER_COUNT
FROM user_entity
WHERE 1 = 1
  AND GENDER <> ''
GROUP BY GENDER
ORDER BY GENDER_COUNT DESC;

--CONTEO DE SEGMENTO RFM POR APPLICATION_USER_ID
SELECT
    SEGMENT_RFM
     ,COUNT(APPLICATION_USER_ID) AS SEGMENT_COUNT
FROM user_entity
WHERE 1 = 1
  AND SEGMENT_RFM <> 'Undefined Segment RFM'
GROUP BY SEGMENT_RFM
ORDER BY SEGMENT_COUNT DESC;

--CONTEO DE PRIME POR APPLICATION_USER_ID
SELECT
    IS_PRIME
     ,COUNT(APPLICATION_USER_ID) AS PRIME_COUNT
FROM user_entity
WHERE 1 = 1
GROUP BY IS_PRIME
ORDER BY PRIME_COUNT DESC;

--CONTEO DE PRIME POR APPLICATION_USER_ID
SELECT
    IS_PRIME
     ,SEGMENT_RFM
     ,GENDER
     ,COUNT(APPLICATION_USER_ID) AS USER_COUNT
FROM user_entity
WHERE 1 = 1
  AND SEGMENT_RFM <> 'Undefined Segment RFM'
  AND GENDER <> ''
GROUP BY IS_PRIME,SEGMENT_RFM,GENDER;

-- CONTEO DE GENERO DE RT POR STOREKEEPER_ID
SELECT
    GENDER_RT
     ,COUNT(STOREKEEPER_ID) AS GENDER_RT_COUNT
FROM rt_entity
WHERE 1 = 1
GROUP BY GENDER_RT;

-- CONTEO DE TIPO DE TRANSPORTE DE RT POR STOREKEEPER_ID
SELECT
    TRANSPORT_MEDIA_TYPE
     ,COUNT(STOREKEEPER_ID) AS TRANSPORT_COUNT
FROM rt_entity
WHERE 1 = 1
GROUP BY TRANSPORT_MEDIA_TYPE;

-- CONTEO DE KIT SIZE DE RT POR STOREKEEPER_ID
SELECT
    DELIVERY_KIT_SIZE
     ,COUNT(STOREKEEPER_ID) AS DELIVERY_KIT_COUNT
FROM rt_entity
WHERE 1 = 1
  AND DELIVERY_KIT_SIZE <> ''
GROUP BY DELIVERY_KIT_SIZE;

-- EDAD MIMIMA DE RT
WITH AGE AS(
    SELECT
        STOREKEEPER_ID
         ,BIRTHDAY_RT
         ,DATETIME(JULIANDAY(DATETIME('NOW'))) - DATETIME(JULIANDAY(BIRTHDAY_RT)) AS AGE_RT
    FROM rt_entity
    WHERE 1 = 1
)
SELECT
    MIN(AGE_RT) AS AGE_RT
FROM AGE
WHERE 1 = 1
  AND BIRTHDAY_RT > '1918-11-16'
  AND BIRTHDAY_RT < '2019-02-12';

-- EDAD MAXIMA DE RT
WITH AGE AS(
    SELECT
        STOREKEEPER_ID
         ,BIRTHDAY_RT
         ,DATETIME(JULIANDAY(DATETIME('NOW'))) - DATETIME(JULIANDAY(BIRTHDAY_RT)) AS AGE_RT
    FROM rt_entity
    WHERE 1 = 1
)
SELECT
    MAX(AGE_RT) AS AGE_RT
FROM AGE
WHERE 1 = 1
  AND BIRTHDAY_RT > '1918-11-16'
  AND BIRTHDAY_RT < '2019-02-12';

-- EDAD PROMEDIO DE RT
WITH AGE AS(
    SELECT
        STOREKEEPER_ID
         ,BIRTHDAY_RT
         ,DATETIME(JULIANDAY(DATETIME('NOW'))) - DATETIME(JULIANDAY(BIRTHDAY_RT)) AS AGE_RT
    FROM rt_entity
    WHERE 1 = 1
)
SELECT
    round(AVG(AGE_RT),0) AS AGE_RT
FROM AGE
WHERE 1 = 1
  AND BIRTHDAY_RT > '1918-11-16'
  AND BIRTHDAY_RT < '2019-02-12';

-- CONTEO DE EDADES DE RT
WITH AGE AS(
    SELECT
        STOREKEEPER_ID
         ,BIRTHDAY_RT
         ,DATETIME(JULIANDAY(DATETIME('NOW'))) - DATETIME(JULIANDAY(BIRTHDAY_RT)) AS AGE_RT
    FROM rt_entity
    WHERE 1 = 1
)
SELECT
    AGE_RT
     ,COUNT(AGE_RT) AS AGE_RT_COUNT
FROM AGE
WHERE 1 = 1
  AND BIRTHDAY_RT > '1918-11-16'
  AND BIRTHDAY_RT < '2019-02-12'
GROUP BY AGE_RT
ORDER BY AGE_RT_COUNT DESC;

-- EDAD MINIMA DE RT POR GENERO
WITH AGE AS(
    SELECT
        STOREKEEPER_ID
         ,BIRTHDAY_RT
         ,GENDER_RT
         ,TRANSPORT_MEDIA_TYPE
         ,DELIVERY_KIT_SIZE
         ,DATETIME(JULIANDAY(DATETIME('NOW'))) - DATETIME(JULIANDAY(BIRTHDAY_RT)) AS AGE_RT
    FROM rt_entity
    WHERE 1 = 1
)
SELECT
    GENDER_RT
     ,TRANSPORT_MEDIA_TYPE
     ,DELIVERY_KIT_SIZE
     ,MIN(AGE_RT) AS AGE_RT_COUNT
FROM AGE
WHERE 1 = 1
  AND BIRTHDAY_RT > '1918-11-16'
  AND BIRTHDAY_RT < '2019-02-12'
GROUP BY GENDER_RT,TRANSPORT_MEDIA_TYPE,DELIVERY_KIT_SIZE
ORDER BY AGE_RT_COUNT DESC;

-- EDAD MAXIMA DE RT POR GENERO
WITH AGE AS(
    SELECT
        STOREKEEPER_ID
         ,BIRTHDAY_RT
         ,GENDER_RT
         ,TRANSPORT_MEDIA_TYPE
         ,DELIVERY_KIT_SIZE
         ,DATETIME(JULIANDAY(DATETIME('NOW'))) - DATETIME(JULIANDAY(BIRTHDAY_RT)) AS AGE_RT
    FROM rt_entity
    WHERE 1 = 1
)
SELECT
    GENDER_RT
     ,TRANSPORT_MEDIA_TYPE
     ,DELIVERY_KIT_SIZE
     ,MAX(AGE_RT) AS AGE_RT_COUNT
FROM AGE
WHERE 1 = 1
  AND BIRTHDAY_RT > '1918-11-16'
  AND BIRTHDAY_RT < '2019-02-12'
GROUP BY GENDER_RT,TRANSPORT_MEDIA_TYPE,DELIVERY_KIT_SIZE
ORDER BY AGE_RT_COUNT DESC;

-- EDAD PROMEDIO DE RT POR GENERO
WITH AGE AS(
    SELECT
        STOREKEEPER_ID
         ,BIRTHDAY_RT
         ,GENDER_RT
         ,TRANSPORT_MEDIA_TYPE
         ,DELIVERY_KIT_SIZE
         ,DATETIME(JULIANDAY(DATETIME('NOW'))) - DATETIME(JULIANDAY(BIRTHDAY_RT)) AS AGE_RT
    FROM rt_entity
    WHERE 1 = 1
)
SELECT
    GENDER_RT
     ,TRANSPORT_MEDIA_TYPE
     ,DELIVERY_KIT_SIZE
     ,ROUND(AVG(AGE_RT),1) AS AGE_RT_COUNT
FROM AGE
WHERE 1 = 1
  AND BIRTHDAY_RT > '1918-11-16'
  AND BIRTHDAY_RT < '2019-02-12'
GROUP BY GENDER_RT,TRANSPORT_MEDIA_TYPE,DELIVERY_KIT_SIZE
ORDER BY AGE_RT_COUNT DESC;

-- CONTEO DE ORDENES DISTINTAS
SELECT
    COUNT(DISTINCT ORDER_ID) AS ORDER_COUNTS
FROM order_entity
WHERE 1 = 1;

-- CONTEO DE METODOS DE PAGO POR ORDEN
SELECT
    PAYMENT_METHOD
     ,COUNT(DISTINCT ORDER_ID) AS ORDER_COUNTS
FROM order_entity
WHERE 1 = 1
GROUP BY PAYMENT_METHOD
ORDER BY ORDER_COUNTS DESC;

-- CONTEO DE METODOS DE PAGO POR RT
SELECT
    PAYMENT_METHOD
     ,COUNT(DISTINCT STOREKEEPER_ID) AS ORDER_COUNTS
FROM order_entity
WHERE 1 = 1
GROUP BY PAYMENT_METHOD
ORDER BY ORDER_COUNTS DESC;

-- CONTEO DE ORDENES DISTINTAS POR RT
SELECT
    COUNT(DISTINCT STOREKEEPER_ID) AS ORDER_COUNTS
FROM order_entity
WHERE 1 = 1;

-- CONTEO DE METODOS DE PAGO POR USUARIO
SELECT
    PAYMENT_METHOD
     ,COUNT(DISTINCT APPLICATION_USER_ID) AS ORDER_COUNTS
FROM order_entity
WHERE 1 = 1
GROUP BY PAYMENT_METHOD
ORDER BY ORDER_COUNTS DESC;

-- CONTEO DE ORDENES DISTINTAS POR USUARIO
SELECT
    COUNT(DISTINCT APPLICATION_USER_ID) AS ORDER_COUNTS
FROM order_entity
WHERE 1 = 1;

-- PROPINA MINIMA
SELECT
    MIN(TIP) AS TIP_MIN
FROM order_entity;

-- SUMA PROPINA
SELECT
    SUM(TIP) AS TIP_MIN
FROM order_entity;

-- PROPINA MAXIMA
SELECT
    MAX(TIP) AS TIP_MAX
FROM order_entity;

-- PROPINA PROMEDIO
SELECT
    AVG(TIP) AS TIP_AVG
FROM order_entity;

-- VALOR MINIMO DE LA ORDEN
SELECT
    MIN(TOTAL_VALUE) AS TOTAL_VALUE_MIN
FROM order_entity;

--SUMA TOTAL DE LA ORDENES
SELECT
    SUM(TOTAL_VALUE) AS TOTAL_VALUE_MIN
FROM order_entity;

-- VALOR MAXIMO DE LA ORDEN
SELECT
    MAX(TOTAL_VALUE) AS TOTAL_VALUE_MIN
FROM order_entity;

-- VALOR PROMEDIO DE LA ORDEN
SELECT
    AVG(TOTAL_VALUE) AS TOTAL_VALUE_AVG
FROM order_entity;

-- VALOR PROMEDIO DE LA ORDEN POR METODO DE PAGO
SELECT
    PAYMENT_METHOD
     ,ROUND(AVG(TOTAL_VALUE),0) AS TOTAL_VALUE_AVG
FROM order_entity
GROUP BY PAYMENT_METHOD;

-- SUMA TOTAL DE LAS ORDENES POR METODO DE PAGO
SELECT
    PAYMENT_METHOD
     ,SUM(TOTAL_VALUE) AS TOTAL_VALUE_SUM
FROM order_entity
GROUP BY PAYMENT_METHOD;

-- VALOR MINIMO DE LA ORDEN POR METODO DE PAGO
SELECT
    PAYMENT_METHOD
     ,MIN(TOTAL_VALUE) AS TOTAL_VALUE_MIN
FROM order_entity
GROUP BY PAYMENT_METHOD;

-- VALOR MAXIMO DE LA ORDEN POR METODO DE PAGO
SELECT
    PAYMENT_METHOD
     ,MAX(TOTAL_VALUE) AS TOTAL_VALUE_MAX
FROM order_entity
GROUP BY PAYMENT_METHOD;

-- TIEMPO MINIMO DE DURACION DE UNA ORDEN
SELECT
    MIN(CAST((JULIANDAY(CLOSED_AT) - JULIANDAY(CREATED_AT))*24*60 AS INTEGER)) AS DURATION_ORDER_MIN
FROM order_entity
WHERE 1 = 1
  AND CLOSED_AT IS NOT NULL;

-- TIEMPO MAXIMO DE DURACION DE UNA ORDEN
SELECT
    MAX(CAST((JULIANDAY(CLOSED_AT) - JULIANDAY(CREATED_AT))*24*60 AS INTEGER)) AS DURATION_ORDER_MAX
FROM order_entity
WHERE 1 = 1
  AND CLOSED_AT IS NOT NULL;

-- TIEMPO PROMEDIO DE DURACION DE UNA ORDEN
SELECT
    AVG(CAST((JULIANDAY(CLOSED_AT) - JULIANDAY(CREATED_AT))*24*60 AS INTEGER)) AS DURATION_ORDER_AVG
FROM order_entity
WHERE 1 = 1
  AND CLOSED_AT IS NOT NULL;

-- TIEMPO MINIMO DE DURACION DE UNA ORDEN POR METODO DE PAGO
SELECT
    PAYMENT_METHOD
     ,MIN(CAST((JULIANDAY(CLOSED_AT) - JULIANDAY(CREATED_AT))*24*60 AS INTEGER)) AS DURATION_ORDER_MIN
FROM order_entity
WHERE 1 = 1
  AND CLOSED_AT IS NOT NULL
GROUP BY PAYMENT_METHOD;

-- TIEMPO MAXIMO DE DURACION DE UNA ORDEN POR METODO DE PAGO
SELECT
    PAYMENT_METHOD
     ,MAX(CAST((JULIANDAY(CLOSED_AT) - JULIANDAY(CREATED_AT))*24*60 AS INTEGER)) AS DURATION_ORDER_MAX
FROM order_entity
WHERE 1 = 1
  AND CLOSED_AT IS NOT NULL
GROUP BY PAYMENT_METHOD;

-- TIEMPO PROMEDIO DE DURACION DE UNA ORDEN POR METODO DE PAGO
SELECT
    PAYMENT_METHOD
     ,AVG(CAST((JULIANDAY(CLOSED_AT) - JULIANDAY(CREATED_AT))*24*60 AS INTEGER)) AS DURATION_ORDER_AVG
FROM order_entity
WHERE 1 = 1
  AND CLOSED_AT IS NOT NULL
GROUP BY PAYMENT_METHOD;

--CONTEO DE PRODUCTOS POR CIUDAD
SELECT
    CITY
     ,COUNT(DISTINCT(PRODUCT_NAME)) AS PRODUCT_COUNT
FROM store_entity
GROUP BY CITY;

--CONTEO DE PRODUCTOS ORDENADOS EN CADA ORDEN
SELECT
    PRODUCT_NAME
     ,COUNT(ORDER_ID) AS ORDER_COUNT
FROM store_entity
GROUP BY PRODUCT_NAME;

--VALOR MINIMO DE CADA PRODUCTO
SELECT
    PRODUCT_NAME
     ,MIN(PRICE) AS MIN_VALUE
FROM store_entity
GROUP BY PRODUCT_NAME;

--VALOR MAXMIMO DE CADA PRODUCTO
SELECT
    PRODUCT_NAME
     ,MAX(PRICE) AS MAX_VALUE
FROM store_entity
GROUP BY PRODUCT_NAME;

--VALOR PROMEDIO DE CADA PRODUCTO
SELECT
    PRODUCT_NAME
     ,AVG(PRICE) AS AVG_VALUE
From store_entity
GROUP BY PRODUCT_NAME;

--CONTEO TIENDAS POR VERTICAL GROUP
SELECT
    VERTICAL_SUB_GROUP
     ,COUNT(STORE_ID) AS STORE_COUNT
From store_entity
GROUP BY VERTICAL_SUB_GROUP;
