
CREATE TABLE "order_entity" (
	"ORDER_ID"	INTEGER NOT NULL UNIQUE,
	"APPLICATION_USER_ID"	INTEGER,
	"CLOSE_AT"	TEXT,
	"CREATED_AT"	TEXT,
	"STOREKEEPER_ID"	INTEGER,
	"PAYMENT_METHOD"	TEXT,
	"TIP"	NUMERIC,
	"TOTAL_VALUE"	NUMERIC,
	PRIMARY KEY("ORDER_ID")
)


CREATE TABLE "rt_entity" (
	"STOREKEEPER_ID"	INTEGER NOT NULL UNIQUE,
	"GENDER_RT"	TEXT,
	"BIRTHDAY_RT"	TEXT,
	"TRANSPORT_MEDIA_TYPE"	TEXT,
	"DELIVERY_KIT_SIZE"	TEXT,
	PRIMARY KEY("STOREKEEPER_ID")
)

CREATE TABLE "store_entity" (
	"STORE_ID"	INTEGER NOT NULL UNIQUE,
	"ORDER_ID"	INTEGER,
	"CITY"	TEXT,
	"PRICE"	INTEGER,
	"PRODUCT_NAME"	TEXT,
	"VERTICAL_SUB_GROUP"	TEXT,
	"CREATED_AT"	TEXT,
	PRIMARY KEY("STORE_ID")
)

CREATE TABLE "user_entity" (
	"APPLICATION_USER_ID"	INTEGER NOT NULL UNIQUE,
	"GENDER"	TEXT,
	"REGISTER_DEVICE"	TEXT,
	"SEGMENT_RFM"	TEXT,
	"IS_PRIME"	TEXT,
	PRIMARY KEY("APPLICATION_USER_ID")
)